### ISSUE TITLE
🪲 Bug Report - Cannot use the old Configfile with the new collector script just posted

### ISSUE THREAD

**Issue by lshaible** [Azure/Azure-Proactive-Resiliency-Library-v2#371] opened 2024-08-24 00:31 UTC
I cannot use the old Configfile with the new collector script just posted. However, the inline parameters worked fine. My configfile is below the command line used and the error is "Invalid ResourceGroup parameters. Exiting...". 
 
.\1_wara_collector.ps1 -Configfile ".\7ESAP1.json"
 
[tenantid]
9356ab53-e6a3-4b3e-ae06-xxxxxxxxxxxx
 
[resourcegroups]
/subscriptions/ee691273-18af-4600-bc24-xxxxxxxxxxxxx/resourceGroups/RG-PROD-ESAP/
/subscriptions/ee691273-18af-4600-bc24-xxxxxxxxxxxxx/resourceGroups/RG-PROD-ESAP-asr/

**Comment by tksh164** [comment] 2024-08-27 07:25
Hi @lshaible, could you try with the latest `1_wara_collector.ps1` (2.1.15)?  Because the config file that you posted looks like to work with the latest script.

https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/blob/main/tools/1_wara_collector.ps1

```powershell
iwr https://aka.ms/aprl/tools/1 -out 1_wara_collector.ps1
```

**Comment by ejhenry** [comment] 2024-08-28 14:35
Confirmed with @lshaible this has been fixed with the latest version of collector script

**Closed by ejhenry** 2024-08-28 14:35 UTC
Labels: Bug :lady_beetle:, Needs: Author Feedback :ear:
