### ISSUE TITLE
❓👂 Question/Feedback - Availability set retirement

### ISSUE THREAD

**Issue by igorjnzl** [Azure/Azure-Proactive-Resiliency-Library-v2#235] opened 2024-06-24 07:47 UTC
## Question/Feedback

Looking at recommendation Migrate VMs using availability sets to VMSS Flex, it states that availability sets will soon be retired, are you able to link the retirement notice / announcement? 

https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Compute/virtualMachines/#migrate-vms-using-availability-sets-to-vmss-flex

**Comment by FallenHoot** [comment] 2024-07-01 07:37
The understanding is that Availability sets have no date for deprecation. Microsoft usually announces this 12 months before, but it is set to be deprecated. Knowing this, it would be up to the judgment on if you should use them or not. Is it more work changing this in the future compared to changing it now. Does VMSS Flex offer the same benefits of AvSets?

**Comment by ejhenry** [comment] 2024-07-01 15:19
@igorjnzl thanks for opening the issue. This recommendation has been verified by the PG and they have been unambiguous with stating customers should not continue to use AvSets.

@FallenHoot before merging your PR we'll need to check with the DRI and PG that they concur with the change.

**Comment by tksh164** [comment] 2024-07-03 04:30
I also curious that `recommendationImpact: High`. It is the highest impact level. Is this so critical at this time? 

In my understanding, that retirement has not yet documented. It is just a recommendation currently. So, this APRL recommendation will surprise customers.

https://learn.microsoft.com/en-us/azure/virtual-machines/availability-set-overview
> We recommend that customers choose virtual machine scale sets with flexible orchestration mode for high availability with the widest range of features. Virtual machine scale sets allow VM instances to be centrally managed, configured, and updated, and will automatically increase or decrease the number of VM instances in response to demand or a defined schedule. Availability sets only offer high availability.

**Comment by ejhenry** [comment] 2024-07-03 15:23
Perhaps we just remove the reference to retirement from the recommendation until the announcement happens? It seems to be taking away from the key component of the recommendation that AvSets do not support zonally deployed VMs. Thoughts?

Regarding impact level, moving off AvSets is critical for customers to achieve zone redundancy so I don't think we want to lower the impact.

**Comment by tksh164** [comment] 2024-07-03 17:30
Thank you @ejhenry. It makes sense to me. So, the recommendation was not intended to the AvSets retirement, it was intended to the AvSets to AZ migration.

If so, I suggest changing the description/title of the recommendation to a more focusing one to the AvSet to AZ migration. Because customers have two options, not only VMSS Flex. The best option depends on the workload, I think.

- Use VMSS Flex
- Place VMs within an AvSet to each AZ (without VMSS Flex)

For example, an AvSet has two ADDS DC VMs. In this case we could not scale out only increase instance count. Is VMSS Flex the best option even in this case?

Also, "use VMSS Flex" is not equal to "use AZ", VMSS FLex supports regional (non-zonal) deployments. I believe. 

- [Update availability set deployments templates and scripts](https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/flexible-virtual-machine-scale-sets-migration-resources#update-availability-set-deployments-templates-and-scripts)
    > You must specify the fault domain count for the Virtual Machine Scale Set. For regional (non-zonal) deployments, Virtual Machine Scale Sets offers the same fault domain guarantees as availability sets.

    ![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2/assets/1618784/82705cea-631b-493b-823a-f156342d3d7e)

And more 2 points on the recommendation:

1. `longDescription`: VMSS Flex has update domains? It seems no update domains.

    - https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Compute/virtualMachines/#migrate-vms-using-availability-sets-to-vmss-flex
        > Availability sets will soon be retired. Migrate workloads from VMs to VMSS Flex for deployment across zones or within the same zone across different fault domains (FDs) and **update domains (UDs)** for better reliability.

    - [Update availability set deployments templates and scripts](https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/flexible-virtual-machine-scale-sets-migration-resources#update-availability-set-deployments-templates-and-scripts)
        > Update domains have been deprecated in Flexible Orchestration mode.

    - [High availability ](https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-orchestration-modes#high-availability)
        > Update Domains
        > Depreciated (platform maintenance performed FD by FD)

2. `learnMoreLink`: I suggest adding the following link.

    - [Migrate deployments and resources to Virtual Machine Scale Sets in Flexible orchestration](https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/flexible-virtual-machine-scale-sets-migration-resources)

**Comment by ejhenry** [comment] 2024-07-15 16:52
@tksh164 there's definitely a lot of underlying complexity with multi-vm deployments, but the guidance from PG that the recommendation aligns with is "all multi-vm deployments should use VMSS flex". The wording of the recommendation longDescription is more focused on one of the particular benefits, AZs, though as you rightly point out AZ use is not a requirement and not all regions support AZs.

I do agree we should remove the reference to UDs and update the learnMoreLink with your suggested URL.

**Comment by ejhenry** [comment] 2024-08-28 14:57
Closing issue as wording has been updated to better reflect current availability set retirement planning, removal UD concept from VMSS flex, and new learnMoreLink.

**Closed by ejhenry** 2024-08-28 14:57 UTC
Labels: Area: Resource Guidance :memo:
